"""empty message

Revision ID: de559b120724
Revises: 6b4c50c71d3d
Create Date: 2022-07-11 18:06:39.590677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de559b120724'
down_revision = '6b4c50c71d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('perfil_image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'perfil_image')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
